resources:

- name: bts-repo
  type: git
  source:
    uri: git@github.com:griga23/boot-twitter-sentiment.git
    branch: master
    private_key: {{bts_private_key}}

- name: visualizer-release
  type: s3
  source:
    bucket: griga-boot-twitter-sentiment
    regexp: boot-twitter-visualizer-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: feeder-release
  type: s3
  source:
    bucket: griga-boot-twitter-sentiment
    regexp: boot-twitter-feeder-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: cf-test
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space-test}}
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space-prod}}
    skip_cert_check: true

jobs:
- name: unit-test
  plan:
  - get: bts-repo
    trigger: true
  - task: unit
    file: bts-repo/ci/tasks/unit.yml

- name: build-binary
  plan:
  - get: bts-repo
    passed: [unit-test]
    trigger: true
  - task: build-artifact
    file: bts-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: feeder-release
    params: {file: binaries/boot-twitter-feeder*.jar }
  - put: visualizer-release
    params: {file: binaries/boot-twitter-visualizer*.jar }

- name: acceptance-tests-feeder
  plan:
  - get: feeder-release
    passed: [build-binary]
    trigger: true
  - get: bts-repo
  - put: cf-test
    params:
      manifest: bts-repo/feeder-manifest.yml
      path: feeder-release/boot-twitter-feeder-*.jar
  - task: acc_test
    file: bts-repo/ci/tasks/test_env.yml
    params:
      TEST_URL: {{TEST_URL}}

- name: acceptance-tests-visualizer
  plan:
  - get: visualizer-release
    passed: [build-binary]
    trigger: true
  - get: bts-repo
  - put: cf-test
    params:
      manifest: bts-repo/visualizer-manifest.yml
      path: visualizer-release/boot-twitter-visualizer-*.jar
  - task: acc_test
    file: bts-repo/ci/tasks/test_env.yml
    params:
      TEST_URL: {{TEST_URL}}

- name: manual-deploy-to-prod-feeder
  plan:
  - get: feeder-release
    passed: [acceptance-tests-feeder]
  - get: visualizer-release
    passed: [acceptance-tests-visualizer]
  - get: bts-repo
  - put: cf-prod
    params:
      manifest: bts-repo/feeder-manifest-prod.yml
      path: feeder-release/boot-twitter-feeder-*.jar

- name: manual-deploy-to-prod-visualizer
  plan:
  - get: feeder-release
    passed: [acceptance-tests-feeder]
  - get: visualizer-release
    passed: [acceptance-tests-visualizer]
  - get: bts-repo
  - put: cf-prod
    params:
      manifest: bts-repo/visualizer-manifest-prod.yml
      path: visualizer-release/boot-twitter-visualizer-*.jar
